import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Axos Capital Investment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head></head>
        <body className="smooth w-full overflow-x-hidden">
          <section className="h-auto   w-full">
            <main className="w-full  p-2 flex-col ov flex items-center justify-center mx-auto max-w-[93%]">
              {children}
            </main>
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
